import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import Footer from "@/components/HomeStuff/Footer";
import Discover from "@/components/HomeStuff/Discover";
import { Image } from "@chakra-ui/react";
import Welcome from "@/components/HomeStuff/Welcome";
import Vision from "@/components/HomeStuff/Vision";
import Mission from "@/components/HomeStuff/Mission";
import Queries from "@/components/Queries/Queries";
import StoreCarousel from "@/components/Store/StoreCarousel";
import Enquire from "@/components/Enquire";
import Navbar from "@/components/HomeStuff/Navbar";
import lookologo from "../assets/images/LOOKO-LOGO.png";
import explore from "../assets/images/down-arrow.png";
import { useEffect, useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.prefetch("/allProducts");
  }, []);
  const ref = useRef(null);
  const Scrolltonext = () => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };
  return (
    <>
      <Head>
        <title>Looko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction={"column"} justify={"space-between"}>
        <Navbar />
        <Discover />
        <Flex
          w={"100%"}
          justify={"center"}
          mt={["-100px", "-40px", "-50px"]}
          zIndex={10}
          mb={["3.5rem", "1rem", "3rem"]}
        >
          <button onClick={Scrolltonext}>
            <Image src={explore.src} width={6} mb={"0.3rem"} />
          </button>
        </Flex>
        <Flex ref={ref} justify={"center"} mr={["0rem", "0rem", "5rem"]}>
          <Image src={lookologo.src} width={400} mb={"0.3rem"} />
        </Flex>
        <Welcome />
        <Vision />
        <Mission />
        <StoreCarousel />
        <Queries />
        <Enquire />
        <Footer />
      </Flex>
    </>
  );
}
